// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using System;
using System.Collections.Generic;
using System.Text;

namespace Utils.Items
{
    //TODO(iharwell): Switch this to simply include the actual line that triggered the ID, rather than using the name and index.
    /// <summary>
    ///   An <see cref="IItemID" /> that was generated by a line-triggered ID system.
    /// </summary>
    public interface ILineTriggeredItemID : IItemID
    {
        /// <summary>
        ///   The name of the trigger line that resulted in this ID.
        /// </summary>
        string TriggerLine { get; set; }

        /// <summary>
        ///   The identifying index of the trigger line that resulted in this ID.
        /// </summary>
        int TriggerLineID { get; set; }

        LineSegment TriggerSegment { get; set; }
    }
}
