// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibAvSharp.Native
{
    [Flags]
    public enum SWS_Flags : int
    {
        SWS_FAST_BILINEAR = 1 << 0,
        SWS_BILINEAR = 1 << 1,
        SWS_BICUBIC = 1 << 2,
        SWS_X = 1 << 3,
        SWS_POINT = 1 << 4,
        SWS_AREA = 1 << 5,
        SWS_BICUBLIN = 1 << 6,
        SWS_GAUSS = 1 << 7,
        SWS_SINC = 1 << 8,
        SWS_LANCZOS = 1 << 9,
        SWS_SPLINE = 1 << 10,
    }

    /*unsafe public struct SwsContext
    {
        public AVClass* av_class;
        public SwsFunc swscale;
        int srcW;
        int srcH;
        int dstH;
        int chrSrcW;
        int chrSrcH;
        int chrDstW;
        int chrDstH;
        int lumXInc;
        int chrXInc;
        int lumYInc;
        int chrYInc;
        AVPixelFormat dstFormat;
        AVPixelFormat srcFormat;
        int dstFormatBpp;
        int srcFormatBpp;
        int dstBpc;
        int srcBpc;
        int chrSrcHSubSample;
        int chrSrcVSubSample;
        int chrDstHSubSample;
        int chrDstVSubSample;
        int vChrDrop;
        int sliceDir;

        // double param[2]
        double param0;
        double param1;

        // SwsContext* cascaded_context[3];
        SwsContext* cascaded_context0;
        SwsContext* cascaded_context1;
        SwsContext* cascaded_context2;

        // int cascaded_tmpStride[4];
        int cascaded_tmpStride0;
        int cascaded_tmpStride1;
        int cascaded_tmpStride2;
        int cascaded_tmpStride3;


        // int cascaded1_tmpStride[4];
        int cascaded1_tmpStride0;
        int cascaded1_tmpStride1;
        int cascaded1_tmpStride2;
        int cascaded1_tmpStride3;

        // uint8_t *cascaded1_tmp[4];
        byte* cascaded1_tmp0;
        byte* cascaded1_tmp1;
        byte* cascaded1_tmp2;
        byte* cascaded1_tmp3;

        int cascaded_mainindex;
        double gamma_value;
        int gamma_flag;
        int is_internal_gamma;
        ushort *gamma;
        ushort *inv_gamma;

        int numDesc;

        //int descIndex[2];
        int descIndex0;
        int descIndex1;

        int numSlice;
        SwsSlice* slice;
        SwsFilterDescriptor* desc;

        #region pal_yuv[256]
        // uint32_t pal_yuv[256];
        public uint pal_yuv0;
        public uint pal_yuv1;
        public uint pal_yuv2;
        public uint pal_yuv3;
        public uint pal_yuv4;
        public uint pal_yuv5;
        public uint pal_yuv6;
        public uint pal_yuv7;
        public uint pal_yuv8;
        public uint pal_yuv9;
        public uint pal_yuv10;
        public uint pal_yuv11;
        public uint pal_yuv12;
        public uint pal_yuv13;
        public uint pal_yuv14;
        public uint pal_yuv15;
        public uint pal_yuv16;
        public uint pal_yuv17;
        public uint pal_yuv18;
        public uint pal_yuv19;
        public uint pal_yuv20;
        public uint pal_yuv21;
        public uint pal_yuv22;
        public uint pal_yuv23;
        public uint pal_yuv24;
        public uint pal_yuv25;
        public uint pal_yuv26;
        public uint pal_yuv27;
        public uint pal_yuv28;
        public uint pal_yuv29;
        public uint pal_yuv30;
        public uint pal_yuv31;
        public uint pal_yuv32;
        public uint pal_yuv33;
        public uint pal_yuv34;
        public uint pal_yuv35;
        public uint pal_yuv36;
        public uint pal_yuv37;
        public uint pal_yuv38;
        public uint pal_yuv39;
        public uint pal_yuv40;
        public uint pal_yuv41;
        public uint pal_yuv42;
        public uint pal_yuv43;
        public uint pal_yuv44;
        public uint pal_yuv45;
        public uint pal_yuv46;
        public uint pal_yuv47;
        public uint pal_yuv48;
        public uint pal_yuv49;
        public uint pal_yuv50;
        public uint pal_yuv51;
        public uint pal_yuv52;
        public uint pal_yuv53;
        public uint pal_yuv54;
        public uint pal_yuv55;
        public uint pal_yuv56;
        public uint pal_yuv57;
        public uint pal_yuv58;
        public uint pal_yuv59;
        public uint pal_yuv60;
        public uint pal_yuv61;
        public uint pal_yuv62;
        public uint pal_yuv63;
        public uint pal_yuv64;
        public uint pal_yuv65;
        public uint pal_yuv66;
        public uint pal_yuv67;
        public uint pal_yuv68;
        public uint pal_yuv69;
        public uint pal_yuv70;
        public uint pal_yuv71;
        public uint pal_yuv72;
        public uint pal_yuv73;
        public uint pal_yuv74;
        public uint pal_yuv75;
        public uint pal_yuv76;
        public uint pal_yuv77;
        public uint pal_yuv78;
        public uint pal_yuv79;
        public uint pal_yuv80;
        public uint pal_yuv81;
        public uint pal_yuv82;
        public uint pal_yuv83;
        public uint pal_yuv84;
        public uint pal_yuv85;
        public uint pal_yuv86;
        public uint pal_yuv87;
        public uint pal_yuv88;
        public uint pal_yuv89;
        public uint pal_yuv90;
        public uint pal_yuv91;
        public uint pal_yuv92;
        public uint pal_yuv93;
        public uint pal_yuv94;
        public uint pal_yuv95;
        public uint pal_yuv96;
        public uint pal_yuv97;
        public uint pal_yuv98;
        public uint pal_yuv99;
        public uint pal_yuv100;
        public uint pal_yuv101;
        public uint pal_yuv102;
        public uint pal_yuv103;
        public uint pal_yuv104;
        public uint pal_yuv105;
        public uint pal_yuv106;
        public uint pal_yuv107;
        public uint pal_yuv108;
        public uint pal_yuv109;
        public uint pal_yuv110;
        public uint pal_yuv111;
        public uint pal_yuv112;
        public uint pal_yuv113;
        public uint pal_yuv114;
        public uint pal_yuv115;
        public uint pal_yuv116;
        public uint pal_yuv117;
        public uint pal_yuv118;
        public uint pal_yuv119;
        public uint pal_yuv120;
        public uint pal_yuv121;
        public uint pal_yuv122;
        public uint pal_yuv123;
        public uint pal_yuv124;
        public uint pal_yuv125;
        public uint pal_yuv126;
        public uint pal_yuv127;
        public uint pal_yuv128;
        public uint pal_yuv129;
        public uint pal_yuv130;
        public uint pal_yuv131;
        public uint pal_yuv132;
        public uint pal_yuv133;
        public uint pal_yuv134;
        public uint pal_yuv135;
        public uint pal_yuv136;
        public uint pal_yuv137;
        public uint pal_yuv138;
        public uint pal_yuv139;
        public uint pal_yuv140;
        public uint pal_yuv141;
        public uint pal_yuv142;
        public uint pal_yuv143;
        public uint pal_yuv144;
        public uint pal_yuv145;
        public uint pal_yuv146;
        public uint pal_yuv147;
        public uint pal_yuv148;
        public uint pal_yuv149;
        public uint pal_yuv150;
        public uint pal_yuv151;
        public uint pal_yuv152;
        public uint pal_yuv153;
        public uint pal_yuv154;
        public uint pal_yuv155;
        public uint pal_yuv156;
        public uint pal_yuv157;
        public uint pal_yuv158;
        public uint pal_yuv159;
        public uint pal_yuv160;
        public uint pal_yuv161;
        public uint pal_yuv162;
        public uint pal_yuv163;
        public uint pal_yuv164;
        public uint pal_yuv165;
        public uint pal_yuv166;
        public uint pal_yuv167;
        public uint pal_yuv168;
        public uint pal_yuv169;
        public uint pal_yuv170;
        public uint pal_yuv171;
        public uint pal_yuv172;
        public uint pal_yuv173;
        public uint pal_yuv174;
        public uint pal_yuv175;
        public uint pal_yuv176;
        public uint pal_yuv177;
        public uint pal_yuv178;
        public uint pal_yuv179;
        public uint pal_yuv180;
        public uint pal_yuv181;
        public uint pal_yuv182;
        public uint pal_yuv183;
        public uint pal_yuv184;
        public uint pal_yuv185;
        public uint pal_yuv186;
        public uint pal_yuv187;
        public uint pal_yuv188;
        public uint pal_yuv189;
        public uint pal_yuv190;
        public uint pal_yuv191;
        public uint pal_yuv192;
        public uint pal_yuv193;
        public uint pal_yuv194;
        public uint pal_yuv195;
        public uint pal_yuv196;
        public uint pal_yuv197;
        public uint pal_yuv198;
        public uint pal_yuv199;
        public uint pal_yuv200;
        public uint pal_yuv201;
        public uint pal_yuv202;
        public uint pal_yuv203;
        public uint pal_yuv204;
        public uint pal_yuv205;
        public uint pal_yuv206;
        public uint pal_yuv207;
        public uint pal_yuv208;
        public uint pal_yuv209;
        public uint pal_yuv210;
        public uint pal_yuv211;
        public uint pal_yuv212;
        public uint pal_yuv213;
        public uint pal_yuv214;
        public uint pal_yuv215;
        public uint pal_yuv216;
        public uint pal_yuv217;
        public uint pal_yuv218;
        public uint pal_yuv219;
        public uint pal_yuv220;
        public uint pal_yuv221;
        public uint pal_yuv222;
        public uint pal_yuv223;
        public uint pal_yuv224;
        public uint pal_yuv225;
        public uint pal_yuv226;
        public uint pal_yuv227;
        public uint pal_yuv228;
        public uint pal_yuv229;
        public uint pal_yuv230;
        public uint pal_yuv231;
        public uint pal_yuv232;
        public uint pal_yuv233;
        public uint pal_yuv234;
        public uint pal_yuv235;
        public uint pal_yuv236;
        public uint pal_yuv237;
        public uint pal_yuv238;
        public uint pal_yuv239;
        public uint pal_yuv240;
        public uint pal_yuv241;
        public uint pal_yuv242;
        public uint pal_yuv243;
        public uint pal_yuv244;
        public uint pal_yuv245;
        public uint pal_yuv246;
        public uint pal_yuv247;
        public uint pal_yuv248;
        public uint pal_yuv249;
        public uint pal_yuv250;
        public uint pal_yuv251;
        public uint pal_yuv252;
        public uint pal_yuv253;
        public uint pal_yuv254;
        public uint pal_yuv255;
        #endregion pal_yuv[256]

        // uint32_t pal_rgb[256];
        #region pal_rgb[256]
        public uint pal_rgb0;
        public uint pal_rgb1;
        public uint pal_rgb2;
        public uint pal_rgb3;
        public uint pal_rgb4;
        public uint pal_rgb5;
        public uint pal_rgb6;
        public uint pal_rgb7;
        public uint pal_rgb8;
        public uint pal_rgb9;
        public uint pal_rgb10;
        public uint pal_rgb11;
        public uint pal_rgb12;
        public uint pal_rgb13;
        public uint pal_rgb14;
        public uint pal_rgb15;
        public uint pal_rgb16;
        public uint pal_rgb17;
        public uint pal_rgb18;
        public uint pal_rgb19;
        public uint pal_rgb20;
        public uint pal_rgb21;
        public uint pal_rgb22;
        public uint pal_rgb23;
        public uint pal_rgb24;
        public uint pal_rgb25;
        public uint pal_rgb26;
        public uint pal_rgb27;
        public uint pal_rgb28;
        public uint pal_rgb29;
        public uint pal_rgb30;
        public uint pal_rgb31;
        public uint pal_rgb32;
        public uint pal_rgb33;
        public uint pal_rgb34;
        public uint pal_rgb35;
        public uint pal_rgb36;
        public uint pal_rgb37;
        public uint pal_rgb38;
        public uint pal_rgb39;
        public uint pal_rgb40;
        public uint pal_rgb41;
        public uint pal_rgb42;
        public uint pal_rgb43;
        public uint pal_rgb44;
        public uint pal_rgb45;
        public uint pal_rgb46;
        public uint pal_rgb47;
        public uint pal_rgb48;
        public uint pal_rgb49;
        public uint pal_rgb50;
        public uint pal_rgb51;
        public uint pal_rgb52;
        public uint pal_rgb53;
        public uint pal_rgb54;
        public uint pal_rgb55;
        public uint pal_rgb56;
        public uint pal_rgb57;
        public uint pal_rgb58;
        public uint pal_rgb59;
        public uint pal_rgb60;
        public uint pal_rgb61;
        public uint pal_rgb62;
        public uint pal_rgb63;
        public uint pal_rgb64;
        public uint pal_rgb65;
        public uint pal_rgb66;
        public uint pal_rgb67;
        public uint pal_rgb68;
        public uint pal_rgb69;
        public uint pal_rgb70;
        public uint pal_rgb71;
        public uint pal_rgb72;
        public uint pal_rgb73;
        public uint pal_rgb74;
        public uint pal_rgb75;
        public uint pal_rgb76;
        public uint pal_rgb77;
        public uint pal_rgb78;
        public uint pal_rgb79;
        public uint pal_rgb80;
        public uint pal_rgb81;
        public uint pal_rgb82;
        public uint pal_rgb83;
        public uint pal_rgb84;
        public uint pal_rgb85;
        public uint pal_rgb86;
        public uint pal_rgb87;
        public uint pal_rgb88;
        public uint pal_rgb89;
        public uint pal_rgb90;
        public uint pal_rgb91;
        public uint pal_rgb92;
        public uint pal_rgb93;
        public uint pal_rgb94;
        public uint pal_rgb95;
        public uint pal_rgb96;
        public uint pal_rgb97;
        public uint pal_rgb98;
        public uint pal_rgb99;
        public uint pal_rgb100;
        public uint pal_rgb101;
        public uint pal_rgb102;
        public uint pal_rgb103;
        public uint pal_rgb104;
        public uint pal_rgb105;
        public uint pal_rgb106;
        public uint pal_rgb107;
        public uint pal_rgb108;
        public uint pal_rgb109;
        public uint pal_rgb110;
        public uint pal_rgb111;
        public uint pal_rgb112;
        public uint pal_rgb113;
        public uint pal_rgb114;
        public uint pal_rgb115;
        public uint pal_rgb116;
        public uint pal_rgb117;
        public uint pal_rgb118;
        public uint pal_rgb119;
        public uint pal_rgb120;
        public uint pal_rgb121;
        public uint pal_rgb122;
        public uint pal_rgb123;
        public uint pal_rgb124;
        public uint pal_rgb125;
        public uint pal_rgb126;
        public uint pal_rgb127;
        public uint pal_rgb128;
        public uint pal_rgb129;
        public uint pal_rgb130;
        public uint pal_rgb131;
        public uint pal_rgb132;
        public uint pal_rgb133;
        public uint pal_rgb134;
        public uint pal_rgb135;
        public uint pal_rgb136;
        public uint pal_rgb137;
        public uint pal_rgb138;
        public uint pal_rgb139;
        public uint pal_rgb140;
        public uint pal_rgb141;
        public uint pal_rgb142;
        public uint pal_rgb143;
        public uint pal_rgb144;
        public uint pal_rgb145;
        public uint pal_rgb146;
        public uint pal_rgb147;
        public uint pal_rgb148;
        public uint pal_rgb149;
        public uint pal_rgb150;
        public uint pal_rgb151;
        public uint pal_rgb152;
        public uint pal_rgb153;
        public uint pal_rgb154;
        public uint pal_rgb155;
        public uint pal_rgb156;
        public uint pal_rgb157;
        public uint pal_rgb158;
        public uint pal_rgb159;
        public uint pal_rgb160;
        public uint pal_rgb161;
        public uint pal_rgb162;
        public uint pal_rgb163;
        public uint pal_rgb164;
        public uint pal_rgb165;
        public uint pal_rgb166;
        public uint pal_rgb167;
        public uint pal_rgb168;
        public uint pal_rgb169;
        public uint pal_rgb170;
        public uint pal_rgb171;
        public uint pal_rgb172;
        public uint pal_rgb173;
        public uint pal_rgb174;
        public uint pal_rgb175;
        public uint pal_rgb176;
        public uint pal_rgb177;
        public uint pal_rgb178;
        public uint pal_rgb179;
        public uint pal_rgb180;
        public uint pal_rgb181;
        public uint pal_rgb182;
        public uint pal_rgb183;
        public uint pal_rgb184;
        public uint pal_rgb185;
        public uint pal_rgb186;
        public uint pal_rgb187;
        public uint pal_rgb188;
        public uint pal_rgb189;
        public uint pal_rgb190;
        public uint pal_rgb191;
        public uint pal_rgb192;
        public uint pal_rgb193;
        public uint pal_rgb194;
        public uint pal_rgb195;
        public uint pal_rgb196;
        public uint pal_rgb197;
        public uint pal_rgb198;
        public uint pal_rgb199;
        public uint pal_rgb200;
        public uint pal_rgb201;
        public uint pal_rgb202;
        public uint pal_rgb203;
        public uint pal_rgb204;
        public uint pal_rgb205;
        public uint pal_rgb206;
        public uint pal_rgb207;
        public uint pal_rgb208;
        public uint pal_rgb209;
        public uint pal_rgb210;
        public uint pal_rgb211;
        public uint pal_rgb212;
        public uint pal_rgb213;
        public uint pal_rgb214;
        public uint pal_rgb215;
        public uint pal_rgb216;
        public uint pal_rgb217;
        public uint pal_rgb218;
        public uint pal_rgb219;
        public uint pal_rgb220;
        public uint pal_rgb221;
        public uint pal_rgb222;
        public uint pal_rgb223;
        public uint pal_rgb224;
        public uint pal_rgb225;
        public uint pal_rgb226;
        public uint pal_rgb227;
        public uint pal_rgb228;
        public uint pal_rgb229;
        public uint pal_rgb230;
        public uint pal_rgb231;
        public uint pal_rgb232;
        public uint pal_rgb233;
        public uint pal_rgb234;
        public uint pal_rgb235;
        public uint pal_rgb236;
        public uint pal_rgb237;
        public uint pal_rgb238;
        public uint pal_rgb239;
        public uint pal_rgb240;
        public uint pal_rgb241;
        public uint pal_rgb242;
        public uint pal_rgb243;
        public uint pal_rgb244;
        public uint pal_rgb245;
        public uint pal_rgb246;
        public uint pal_rgb247;
        public uint pal_rgb248;
        public uint pal_rgb249;
        public uint pal_rgb250;
        public uint pal_rgb251;
        public uint pal_rgb252;
        public uint pal_rgb253;
        public uint pal_rgb254;
        public uint pal_rgb255;

        #endregion pal_rgb[256]

        int lastInLumBuf;
        int lastInChrBuf;
        int lumBufIndex;
        int chrBufIndex;

        byte* formatConvBuffer;
        int needAlpha;
        short* hLumFilter;
        short* hChrFilter;
        short* vLumFilter;
        short* vChrFilter;
        int* hLumFilterPos;
        int* hChrFilterPos;
        int* vLumFilterPos;
        int* vChrFilterPos;
        int hLumFilterSize;
        int hChrFilterSize;
        int vLumFilterSize;
        int vChrFilterSize;

        int lumMmxextFilterCodeSize;
        int chrMmxextFilterCodeSize;  //< Runtime-generated MMXEXT horizontal fast bilinear scaler code size for chroma planes.
        byte *lumMmxextFilterCode;    //< Runtime-generated MMXEXT horizontal fast bilinear scaler code for luma/alpha planes.
        byte *chrMmxextFilterCode;    //< Runtime-generated MMXEXT horizontal fast bilinear scaler code for chroma planes.

        int canMMXEXTBeUsed;
        int warned_unuseable_bilinear;

        int dstY;
        int flags;
        void* yuvTable;
        // DECLARE_ALIGNED(16, int, table_gV)[256 + 2*YUVRGB_TABLE_HEADROOM];
    }*/
}
